xcode: latest

# Define workflow
workflows:

  download-artifacts:
    name: Download Artifacts
    instance_type: mac_mini
    depends_on: ios-build

    scripts:
      - name: Download artifact
        script: |
          curl -o output.zip $CM_ARTIFACT_PATH