workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1

    scripts:
      - name: Build
        script: |
          # Your build commands here
          flutter build ios --release

    artifacts:
      - build/ios/Runner.app # Define the path to the artifact you want to save

  download-artifacts:
    name: Download Artifacts
    max_build_duration: 120
    instance_type: mac_mini_m1

    dependencies:
      - sample-workflow # Reference the previous workflow

    scripts:
      - name: Download Artifacts
        script: |
          # Download the artifact from the previous workflow
          curl -O $CM_ARTIFACT_PATH
