# Specify Xcode version
xcode: latest

# Define workflows
workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_pro
    # Generate IPA artifact
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    scripts:
      - name: Set up keychain to sign iOS app
        script: |
          # Add certificate and provisioning profile from Codemagic UI
          keychain initialize
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build IPA for distribution
        script: |
          flutter build ios --release --build-name=1.0.0 --build-number=$CM_BUILD_NUMBER
          cd build/ios/ipa
          zip -r app.ipa Payload
      - name: Export $CM_ARTIFACT_PATH
        script: |
          echo "The artifact path is $CM_ARTIFACT_PATH"

  download-artifacts:
    name: Download Artifacts
    instance_type: mac_mini
    depends_on:
      - ios-build
    scripts:
      - name: Download artifact
        script: |
          curl -o output.zip $CM_ARTIFACT_PATH