# Specify Xcode version
xcode: latest

# Define workflows 
workflows:

  ios-build:
    name: iOS Build
    instance_type: mac_pro
    
    scripts:
      - name: Flutter build iOS
        script: flutter build ios --release

    artifacts:
      - build/app/outputs/apk/**/*.apk
      - build/app/outputs/bundle/**/*.aab

  android-build:
    name: Android Build
    instance_type: linux_docker
    
    scripts:
      - name: Flutter build Android
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/**/*.apk
      - build/app/outputs/bundle/**/*.aab

  export-artifacts:
    name: Export Artifacts
    instance_type: linux_docker
    depends_on:
      - ios-build
      - android-build

    scripts:
      - name: Export artifacts
        script: |
          echo "iOS artifact path: $CM_IOS_ARTIFACT_PATH"
          echo "Android artifact path: $CM_ANDROID_ARTIFACT_PATH"

